typography_spectrum: 0.4478673385456204
color:
  saturation: 0.5547798
  brandStrength: 0.03270020731724799
  lightness: 0
  brandColors:
    - '#29363B'
    - '#9AB899'
    - '#FCCEAB'
    - '#F2847F'
    - '#E84B62'
  rhythmicContrast: 0.5204082
layout_spectrum: 0
author:
  name: David van Ballegooijen
  email: davidvb.private@gmail.com
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/03db3477-4965-4419-8050-3580fb628d55.png
name: WELCOME HUMAN
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
title: INTERACTION MAN
description: Functional Eye Candy & Enjoyable Usability
