typography_spectrum: 0.574813169427216
color:
  brandStrength: 0.7882483215071261
  lightness: 0.09874838287942111
  saturation: 0.492283962899819
  rhythmicContrast: 0.8184917378239334
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
layout_spectrum: 0.617111895699054
author:
  name: David van Ballegooijen
  email: davidvb.private@gmail.com
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/03db3477-4965-4419-8050-3580fb628d55.png
name: interaction man
title: finding transcendence
description: ~ by feeding the obsession ~
